services:
  app:
    container_name: basket_service_2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend
    entrypoint: [ "sh", "/app/entrypoint.sh" ]

networks:
  backend:
    external: true
