services:
  app:
    container_name: basket_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8989:8989"
    env_file:
      - .env
    command: python main.py
    networks:
      - backend

networks:
  backend:
    external: true
