"""add checkout_stage

Revision ID: 3eba272e96ba
Revises: f163463b2b4a
Create Date: 2024-10-10 03:26:13.808038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3eba272e96ba"
down_revision: Union[str, None] = "f163463b2b4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "baskets",
        sa.Column(
            "checkout_stage",
            sa.Enum("CREATED", "IN_PROGRESS", name="checkoutstageschema"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("baskets", "checkout_stage")
    # ### end Alembic commands ###
