"""add user_id in order

Revision ID: d9ec6265225c
Revises: 3eba272e96ba
Create Date: 2024-10-14 03:20:12.527495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9ec6265225c"
down_revision: Union[str, None] = "3eba272e96ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
