"""+поля о обработчике ордера

Revision ID: 0483b8f634ca
Revises: b50a8ba348bb
Create Date: 2024-08-15 15:20:18.801242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0483b8f634ca"
down_revision: Union[str, None] = "b50a8ba348bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("manager_executive", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("manager_mailbox", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "manager_mailbox")
    op.drop_column("orders", "manager_executive")
    # ### end Alembic commands ###
