"""+ выбор статуса ордера

Revision ID: bccd92c19b7c
Revises: 0483b8f634ca
Create Date: 2024-08-19 23:54:50.376206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bccd92c19b7c"
down_revision: Union[str, None] = "0483b8f634ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
