"""create tables

Revision ID: b3ecd63cbad8
Revises: 
Create Date: 2024-07-31 17:58:50.974236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3ecd63cbad8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baskets",
        sa.Column("uuid_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("basket_items", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("created_at"),
        sa.UniqueConstraint("uuid_id"),
    )
    op.create_table(
        "orders",
        sa.Column("uuid_id", sa.String(), nullable=False),
        sa.Column("order_status", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("shipping_city", sa.String(), nullable=False),
        sa.Column("delivery_address", sa.String(), nullable=True),
        sa.Column(
            "delivery_type",
            sa.Enum("PICKUP", "DELIVERY", name="deliverytype"),
            nullable=True,
        ),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uuid_id"],
            ["baskets.uuid_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("baskets")
    # ### end Alembic commands ###
