"""init

Revision ID: b50a8ba348bb
Revises: 
Create Date: 2024-08-07 23:51:21.718157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b50a8ba348bb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baskets",
        sa.Column("uuid_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("basket_items", sa.JSON(), nullable=True),
        sa.Column("gift_items", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("created_at"),
        sa.UniqueConstraint("uuid_id"),
    )
    op.create_table(
        "orders",
        sa.Column("uuid_id", sa.String(), nullable=False),
        sa.Column(
            "order_status",
            sa.Enum("NEW", "INWORK", "COMPLITED", name="orderstatustype"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("shipping_city", sa.String(), nullable=False),
        sa.Column("delivery_address", sa.String(), nullable=True),
        sa.Column(
            "delivery_type",
            sa.Enum("DELIVERY", "PICKUP", name="deliverytype"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uuid_id"],
            ["baskets.uuid_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("baskets")
    # ### end Alembic commands ###
